import { PartPreset } from '../types';

export const PART_PRESETS: PartPreset[] = [
  {
    name: 'Chain',
    category: 'drivetrain',
    icon: 'link-variant',
    serviceIntervalKm: 500,
    replaceIntervalKm: 2000,
    serviceIntervalDays: 60,
    replaceIntervalDays: 365,
  },
  {
    name: 'Cassette',
    category: 'drivetrain',
    icon: 'cog',
    serviceIntervalKm: null,
    replaceIntervalKm: 6000,
    serviceIntervalDays: null,
    replaceIntervalDays: null,
  },
  {
    name: 'Chainring',
    category: 'drivetrain',
    icon: 'cog-outline',
    serviceIntervalKm: null,
    replaceIntervalKm: 10000,
    serviceIntervalDays: null,
    replaceIntervalDays: null,
  },
  {
    name: 'Rear Derailleur Cable',
    category: 'cables',
    icon: 'cable-data',
    serviceIntervalKm: 3000,
    replaceIntervalKm: 8000,
    serviceIntervalDays: 180,
    replaceIntervalDays: 730,
  },
  {
    name: 'Front Derailleur Cable',
    category: 'cables',
    icon: 'cable-data',
    serviceIntervalKm: 3000,
    replaceIntervalKm: 8000,
    serviceIntervalDays: 180,
    replaceIntervalDays: 730,
  },
  {
    name: 'Brake Cable (Front)',
    category: 'cables',
    icon: 'cable-data',
    serviceIntervalKm: 2000,
    replaceIntervalKm: 6000,
    serviceIntervalDays: 180,
    replaceIntervalDays: 730,
  },
  {
    name: 'Brake Cable (Rear)',
    category: 'cables',
    icon: 'cable-data',
    serviceIntervalKm: 2000,
    replaceIntervalKm: 6000,
    serviceIntervalDays: 180,
    replaceIntervalDays: 730,
  },
  {
    name: 'Brake Pads (Rim)',
    category: 'brakes',
    icon: 'hand-back-left',
    serviceIntervalKm: 1000,
    replaceIntervalKm: 3000,
    serviceIntervalDays: null,
    replaceIntervalDays: 730,
  },
  {
    name: 'Brake Pads (Disc)',
    category: 'brakes',
    icon: 'disc',
    serviceIntervalKm: 2000,
    replaceIntervalKm: 6000,
    serviceIntervalDays: null,
    replaceIntervalDays: 730,
  },
  {
    name: 'Brake Rotor',
    category: 'brakes',
    icon: 'circle-outline',
    serviceIntervalKm: null,
    replaceIntervalKm: 15000,
    serviceIntervalDays: null,
    replaceIntervalDays: null,
  },
  {
    name: 'Front Tyre',
    category: 'tyres',
    icon: 'tire',
    serviceIntervalKm: null,
    replaceIntervalKm: 8000,
    serviceIntervalDays: null,
    replaceIntervalDays: 1095,
  },
  {
    name: 'Rear Tyre',
    category: 'tyres',
    icon: 'tire',
    serviceIntervalKm: null,
    replaceIntervalKm: 5000,
    serviceIntervalDays: null,
    replaceIntervalDays: 1095,
  },
  {
    name: 'Inner Tubes',
    category: 'tyres',
    icon: 'circle-double',
    serviceIntervalKm: null,
    replaceIntervalKm: null,
    serviceIntervalDays: null,
    replaceIntervalDays: 730,
  },
  {
    name: 'Fork Service (Suspension)',
    category: 'suspension',
    icon: 'ski',
    serviceIntervalKm: 10000,
    replaceIntervalKm: null,
    serviceIntervalDays: 365,
    replaceIntervalDays: null,
  },
  {
    name: 'Rear Shock Service',
    category: 'suspension',
    icon: 'sine-wave',
    serviceIntervalKm: 10000,
    replaceIntervalKm: null,
    serviceIntervalDays: 365,
    replaceIntervalDays: null,
  },
  {
    name: 'Bar Tape / Grips',
    category: 'other',
    icon: 'hand-left',
    serviceIntervalKm: null,
    replaceIntervalKm: null,
    serviceIntervalDays: null,
    replaceIntervalDays: 365,
  },
  {
    name: 'Bottom Bracket',
    category: 'drivetrain',
    icon: 'axis-z-rotate-clockwise',
    serviceIntervalKm: 5000,
    replaceIntervalKm: 20000,
    serviceIntervalDays: null,
    replaceIntervalDays: null,
  },
  {
    name: 'Wheel Bearings',
    category: 'other',
    icon: 'circle-slice-8',
    serviceIntervalKm: 5000,
    replaceIntervalKm: 20000,
    serviceIntervalDays: null,
    replaceIntervalDays: null,
  },
  {
    name: 'Cleats',
    category: 'other',
    icon: 'shoe-cleat',
    serviceIntervalKm: null,
    replaceIntervalKm: 5000,
    serviceIntervalDays: null,
    replaceIntervalDays: 730,
  },
  {
    name: 'General Service',
    category: 'other',
    icon: 'wrench',
    serviceIntervalKm: 1000,
    replaceIntervalKm: null,
    serviceIntervalDays: 90,
    replaceIntervalDays: null,
  },
];

export const CATEGORY_ICONS: Record<string, string> = {
  drivetrain: 'cog',
  brakes: 'hand-back-left',
  tyres: 'tire',
  cables: 'cable-data',
  suspension: 'ski',
  other: 'wrench',
};
